swagger: '2.0'
info:
  title: Heros
  version: "0.0.1-ALPHA"
  description: Simple example how to use connexion + flask
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"

paths:
{% include 'hero.yaml' %}
definitions:
{% include 'hero_definitions.yaml' %}
